apiVersion: v1
kind: Service
metadata:
  name: atticstat
  labels:
    app: atticstat
spec:
  ports:
    - port: 80
  selector:
    app: atticstat
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: atticstat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atticstat
  labels:
    app: atticstat
spec:
  selector:
    matchLabels:
      app: atticstat
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: atticstat
        tier: frontend
    spec:
      containers:
        - image: atticstat:6.2.1-apache
          name: atticstat
          env:
            - name: atticstat_DB_HOST
              value: atticstat-mysql
            - name: atticstat_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
            - name: atticstat_DB_USER
              value: atticstat
          ports:
            - containerPort: 80
              name: atticstat
          volumeMounts:
            - name: atticstat-persistent-storage
              mountPath: /var/www/html
      volumes:
        - name: atticstat-persistent-storage
          persistentVolumeClaim:
            claimName: wp-pv-claim
