services:

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${PG_DB_USER}
      POSTGRES_PASSWORD: ${PG_DB_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
    volumes:
      - pg_db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  balancer:
    image: nginx:alpine
    working_dir: /app
    depends_on:
      - php-fpm
    volumes:
      - ./src/:/app/
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  php-fpm:
    build:
      context: docker/php-fpm/
      target: debug
    restart: always
    working_dir: /app
    volumes:
      - ./src:/app
    environment:
      PHP_IDE_CONFIG: "serverName=atticpool.lc"
    extra_hosts:
      - host.docker.internal:host-gateway

  # Admin Panels
  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080

volumes:
  pg_db_data: