services:

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${PG_DB_USER}
      POSTGRES_PASSWORD: ${PG_DB_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
    volumes:
      - pg_db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  balancer:
    image: nginx:alpine
    working_dir: /var/apl
    depends_on:
      - php-fpm
    volumes:
      - ./src/:/var/apl/
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  php-fpm:
    build:
      context: docker/php-fpm/
    restart: always
    working_dir: /var/apl
    volumes:
      - ./src:/var/apl

  # Admin Panels
  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080

volumes:
  pg_db_data: